---
driver:
  # DOCKER_BUILDKIT=0 kitchen create
  # https://github.com/test-kitchen/kitchen-docker/issues/337
  name: docker

provisioner:
  name: ansible_playbook
  hosts: all
  roles_path: ./roles
  playbook: ./playbooks/playbook.yml
  require_ansible_omnibus: false
  require_chef_for_busser: false

platforms:
  - name: centos-7
    driver_config:
      platform: centos
      image: centos/systemd
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      privileged: true
      provision_command:
        - yum -y install epel-release
        - yum -y install ansible
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
      forward:
        - 80:80
      run_command: /usr/sbin/init

verifier:
  name: shell
  command: >
    py.test --color=yes
    --hosts="paramiko://ec2-user@${KITCHEN_HOSTNAME}:22?ssh_identity_file=~/.ssh/test-fr.pem"
    "./roles/httpd/test/integration/default"

suites:
  - name: default
